# Cut a release whenever a new tag is pushed to the repo.
name: Release

on:
  # Can be triggered from the tag.yaml workflow
  workflow_call:
  # Or, developers can manually push a tag from their clone
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    uses: bazel-contrib/.github/.github/workflows/release_ruleset.yaml@v5
    with:
      prerelease: false
      release_files: rules_lint-*.tar.gz
